### ISSUE TITLE
can't execute file: /Users/npetersohn/dev/tracegl/trace/trace_server.js

### ISSUE THREAD

**Issue by snackycracky** [traceglMPL/tracegl#11]
the command refers to the bin/server.js file of this boilerplate https://github.com/erikras/react-redux-universal-hot-example with the -nolib option

```

[trace.GL] See your code. 
[trace.GL] WebGL trace UI: http://0.0.0.0:2000
[piping] can't execute file: /Users/npetersohn/dev/tracegl/trace/trace_server.js
[piping] error given was: Error: Cannot find module './instrument'
    at Function.Module._resolveFilename (module.js:336:15)
    at /Users/npetersohn/dev/tracegl/core/define.js:67:20
    at Object.<anonymous> (/Users/npetersohn/dev/tracegl/trace/trace_server.js:23:19)
    at module.exports.global.define (/Users/npetersohn/dev/tracegl/core/define.js:80:18)
    at Object.<anonymous> (/Users/npetersohn/dev/tracegl/trace/trace_server.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Module._load (module.js:310:12)
    at Function.module._load (/Users/npetersohn/dev/someapp/node_modules/piping/lib/launcher.js:32:16)
[piping] further repeats of this error will be suppressed...

```

**Comment by snackycracky** [comment]
didn't copy to global
